# Generated by Django 4.0 on 2022-12-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_post_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_tag',
        ),
    ]
