# Generated by Django 4.0 on 2022-12-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
